add tests
Signed-off-by: Scott Hebert <scoheb@gmail.com>

diff --git a/tasks/request-and-upload-signature/request-and-upload-signature.yaml b/tasks/request-and-upload-signature/request-and-upload-signature.yaml
--- a/tasks/request-and-upload-signature/request-and-upload-signature.yaml
+++ b/tasks/request-and-upload-signature/request-and-upload-signature.yaml
@@ -7,23 +7,13 @@ spec:
   description: >-
     Tekton task to request and upload a simple signature.
 
-    Why does this task use stepactions?
-
     - This task is meant to be used in an internal pipeline that can be triggered frequently
       and is expected to complete as quickly as possible.
 
-    -  This task used to be split into separate tasks (request and upload) and required a PV
-       to exchange data between the two tasks.
-
-    -  By combining the two tasks into once, you reduce the amount of pods that are needed. In addition, when using
-       stepactions, you can exchange data between steps using `steps.request-signature.results.signature_data_file`.
-       This then helps remove the need for a PV to back a workspace. An emptyDir can be used.
   params:
     - description: A docker image of operator-pipeline-images for the steps to run in.
       name: pipeline_image
       default: "quay.io/redhat-isv/operator-pipelines-images:released"
-    - name: config_map_name
-      description: Name of a configmap with pipeline configuration
     - description: Manifest digest for the signed content, usually in the format sha256:xxx
       name: manifest_digest
     - description: Docker reference for the signed content, e.g. registry.redhat.io/redhat/community-operator-index:v4.9
@@ -57,73 +47,128 @@ spec:
     - default: https://pyxis.engineering.redhat.com
       description: Pyxis instance to upload the signature to.
       name: pyxis_url
-    - name: taskGitUrl
+    - name: signature_data_file
       type: string
-      description: The url to the git repo where the release-service-catalog tasks to be used are stored
-      default: https://github.com/konflux-ci/release-service-catalog.git
-    - name: taskGitRevision
-      type: string
-      description: The revision in the taskGitUrl repo to be used
+      description: The file where the signing response should be placed
+      default: "signing_response.json"
   steps:
     - name: request-signature
-      params:
-        - name: pipeline_image
-          value: "$(params.pipeline_image)"
+      image: "$(params.pipeline_image)"
+      workingDir: "$(workspaces.data.path)"
+      env:
+        - name: UmbCert
+          valueFrom:
+            secretKeyRef:
+              name: $(params.ssl_cert_secret_name)
+              key: $(params.ssl_cert_file_name)
+        - name: UmbKey
+          valueFrom:
+            secretKeyRef:
+              name: $(params.ssl_cert_secret_name)
+              key: $(params.ssl_key_file_name)
+        - name: UMB_CERT_PATH
+          value: "/tmp/crt"
+        - name: UMB_KEY_PATH
+          value: "/tmp/key"
         - name: manifest_digest
-          value: "$(params.manifest_digest)"
+          value: $(params.manifest_digest)
         - name: reference
-          value: "$(params.reference)"
+          value: $(params.reference)
         - name: requester
-          value: "$(params.requester)"
+          value: $(params.requester)
         - name: sig_key_id
-          value: "$(params.sig_key_id)"
+          value: $(params.sig_key_id)
         - name: sig_key_name
-          value: "$(params.sig_key_name)"
-        - name: umb_ssl_secret_name
-          value: "$(params.ssl_cert_secret_name)"
-        - name: umb_ssl_cert_secret_key
-          value: "$(params.ssl_cert_file_name)"
-        - name: umb_ssl_key_secret_key
-          value: "$(params.ssl_key_file_name)"
+          value: $(params.sig_key_name)
         - name: umb_client_name
-          value: "$(params.umb_client_name)"
-        - name: umb_url
-          value: "$(params.umb_url)"
+          value: $(params.umb_client_name)
         - name: umb_listen_topic
-          value: "$(params.umb_listen_topic)"
+          value: $(params.umb_listen_topic)
         - name: umb_publish_topic
-          value: "$(params.umb_publish_topic)"
-      ref:
-        resolver: git
-        params:
-          - name: url
-            value: $(params.taskGitUrl)
-          - name: revision
-            value: $(params.taskGitRevision)
-          - name: pathInRepo
-            value: stepactions/request-signature/request-signature.yaml
-    - name: upload-signature
-      params:
-        - name: pipeline_image
-          value: "$(params.pipeline_image)"
+          value: $(params.umb_publish_topic)
+        - name: umb_url
+          value: $(params.umb_url)
         - name: signature_data_file
-          value: "$(steps.request-signature.results.signature_data_file)"
-        - name: pyxis_ssl_secret_name
-          value: "$(params.ssl_cert_secret_name)"
-        - name: pyxis_ssl_cert_secret_key
-          value: "$(params.ssl_cert_file_name)"
-        - name: pyxis_ssl_key_secret_key
-          value: "$(params.ssl_key_file_name)"
+          value: "$(params.signature_data_file)"
+      script: |
+        #!/usr/bin/env /bin/bash
+        set -x
+        
+        MAX_RETRIES=3
+        RETRY_DELAY=5 # Initial delay
+        
+        set +x
+        # This helps with Shellcheck warning
+        echo "${UmbCert:?}" > /tmp/crt
+        echo "${UmbKey:?}" > /tmp/key
+        set -x
+        
+        echo "Requesting signing from RADAS"
+        for ((i=1; i<=MAX_RETRIES; i++)); do
+          if request-signature \
+            --manifest-digest "${manifest_digest}" \
+            --output "${signature_data_file:?}" \
+            --reference "${reference}" \
+            --requester "${requester}" \
+            --sig-key-id "${sig_key_id}" \
+            --sig-key-name "${sig_key_name}" \
+            --umb-client-name "${umb_client_name}" \
+            --umb-listen-topic "${umb_listen_topic}" \
+            --umb-publish-topic "${umb_publish_topic}" \
+            --umb-url "${umb_url}" \
+            --verbose
+          then
+            echo "request-signature command succeeded."
+            break
+          elif [ $i -eq $MAX_RETRIES ]; then
+            echo "Max retries reached. Exiting."
+            exit 1
+          else
+            echo "Attempt $i failed. Retrying in $RETRY_DELAY seconds..."
+            sleep $RETRY_DELAY
+            RETRY_DELAY=$((RETRY_DELAY * 2))  # Exponential backoff
+          fi
+        done
+        
+        SIG_DATA=$(cat "${signature_data_file:?}")
+        echo "${SIG_DATA}"
+        echo "signature data file: ${signature_data_file:?}"
+    - name: upload-signature
+      image: "$(params.pipeline_image)"
+      workingDir: "$(workspaces.data.path)"
+      env:
+        - name: PyxisCert
+          valueFrom:
+            secretKeyRef:
+              name: $(params.ssl_cert_secret_name)
+              key: $(params.ssl_cert_file_name)
+        - name: PyxisKey
+          valueFrom:
+            secretKeyRef:
+              name: $(params.ssl_cert_secret_name)
+              key: $(params.ssl_key_file_name)
+        - name: PYXIS_CERT_PATH
+          value: "/tmp/pyxisCert"
+        - name: PYXIS_KEY_PATH
+          value: "/tmp/pyxisKey"
         - name: pyxis_url
-          value: "$(params.pyxis_url)"
-      ref:
-        resolver: git
-        params:
-          - name: url
-            value: $(params.taskGitUrl)
-          - name: revision
-            value: $(params.taskGitRevision)
-          - name: pathInRepo
-            value: stepactions/upload-signature/upload-signature.yaml
+          value: $(params.pyxis_url)
+        - name: signature_data_file
+          value: "$(params.signature_data_file)"
+      script: |
+        #!/bin/bash
+        set -xe
+        
+        set +x
+        # This helps with Shellcheck warning
+        echo "${PyxisCert:?}" > /tmp/pyxisCert
+        echo "${PyxisKey:?}" > /tmp/pyxisKey
+        set -x
+        
+        echo "Signature verified. Uploading to Pyxis sigstore"
+        upload-signature \
+          --pyxis-url "${pyxis_url:?}" \
+          --signature-data "${signature_data_file:?}" \
+          --verbose
   workspaces:
-    - name: source
+    - name: data
