feat(RELEASE-1387): use trusted artifacts
- in an effort to move away from PVCs, we are trying
  trusted artifacts based on
  https://github.com/konflux-ci/build-trusted-artifacts/tree/main
- tasks that have been updated now support 2 modes:
  - PVC based workspaces
  - Trusted artifacts with emptyDir workspaces

Summary:
- StepActions that support trusted artifacts have been added.
- all tasks used in the rh-advisory pipeline have been converted to
  support trusted artifacts mode
- pipelines have been updated to include the stepAction git related
  parameters.
- pipelines that use apply-mapping have had the workspace used for
  the apply-mapping task renamed to be in line with other tasks.
- The task verify-enterprise-contract has been renamed to
  verify-conforma and has been refactored to use the new git-resolved
  task verify-conforma-konflux-ta

- CI changes:
  - CI now attempts to detect if a Trusted Artifacts based task
     has been changed and runs the tests with trusted artifacts enabled.
  - tests now create an on-local-cluster registry.
  - CI will find stepactions and install them on local cluster
    and update git resolvers to be direct cluster resolvers

requires https://github.com/konflux-ci/release-service/pull/666
for use on real clusters

Signed-off-by: Scott Hebert <scoheb@gmail.com>

diff --git a/tasks/managed/run-file-updates/run-file-updates.yaml b/tasks/managed/run-file-updates/run-file-updates.yaml
--- a/tasks/managed/run-file-updates/run-file-updates.yaml
+++ b/tasks/managed/run-file-updates/run-file-updates.yaml
@@ -4,7 +4,7 @@ kind: Task
 metadata:
   name: run-file-updates
   labels:
-    app.kubernetes.io/version: "3.0.1"
+    app.kubernetes.io/version: "4.0.0"
   annotations:
     tekton.dev/pipelines.minVersion: "0.12.1"
     tekton.dev/tags: release
@@ -46,33 +46,141 @@ spec:
     - name: taskGitRevision
       type: string
       description: The revision in the taskGitUrl repo to be used
+    - name: ociStorage
+      description: The OCI repository where the Trusted Artifacts are stored.
+      type: string
+      default: "empty"
+    - name: ociArtifactExpiresAfter
+      description: Expiration date for the trusted artifacts created in the
+        OCI repository. An empty string means the artifacts do not expire.
+      type: string
+      default: "1d"
+    - name: trustedArtifactsDebug
+      description: Flag to enable debug logging in trusted artifacts. Set to a non-empty string to enable.
+      type: string
+      default: ""
+    - name: orasOptions
+      description: oras options to pass to Trusted Artifacts calls
+      type: string
+      default: ""
+    - name: sourceDataArtifact
+      type: string
+      default: ""
+    - name: subdirectory
+      description: Subdirectory inside the workspace to be used
+      type: string
+      default: ""
+    - name: dataDir
+      description: The location where data will be stored
+      type: string
+      default: $(workspaces.data.path)
+    - name: stepActionGitUrl
+      type: string
+      description: The url to the git repo where the release-service-catalog stepActions to be used are stored
+      default: https://github.com/konflux-ci/release-service-catalog.git
+    - name: stepActionGitRevision
+      type: string
+      description: The revision in the stepActionGitUrl repo to be used
+      default: production
   results:
     - name: mergeRequestUrl
       description: URL of MR that was created
+    - description: Produced trusted data artifact
+      name: sourceDataArtifact
+      type: string
   workspaces:
     - name: data
       description: Workspace where the file updates to apply are defined
+  volumes:
+    - name: workdir
+      emptyDir: {}
+  stepTemplate:
+    volumeMounts:
+      - mountPath: /var/workdir
+        name: workdir
+    env:
+      - name: IMAGE_EXPIRES_AFTER
+        value: $(params.ociArtifactExpiresAfter)
+      - name: "ORAS_OPTIONS"
+        value: "$(params.orasOptions)"
+      - name: "DEBUG"
+        value: "$(params.trustedArtifactsDebug)"
+      - name: "HOME"
+        value: "/tekton/home"
   steps:
+    - name: skip-trusted-artifact-operations
+      ref:
+        resolver: "git"
+        params:
+          - name: url
+            value: $(params.stepActionGitUrl)
+          - name: revision
+            value: $(params.stepActionGitRevision)
+          - name: pathInRepo
+            value: stepactions/skip-trusted-artifact-operations/skip-trusted-artifact-operations.yaml
+      params:
+        - name: ociStorage
+          value: $(params.ociStorage)
+        - name: subdirectory
+          value: $(params.subdirectory)
+        - name: dataDir
+          value: $(params.dataDir)
+    - name: use-trusted-artifact
+      ref:
+        resolver: "git"
+        params:
+          - name: url
+            value: $(params.stepActionGitUrl)
+          - name: revision
+            value: $(params.stepActionGitRevision)
+          - name: pathInRepo
+            value: stepactions/use-trusted-artifact/use-trusted-artifact.yaml
+      params:
+        - name: dataDir
+          value: $(params.dataDir)
+        - name: subdirectory
+          value: $(params.subdirectory)
+        - name: sourceDataArtifact
+          value: $(params.sourceDataArtifact)
     - name: run-script
       image: quay.io/konflux-ci/release-service-utils:0f82be4be43294b6a96846d87ef7f7c0b9e34267
+      onError: continue
       script: |
         #!/bin/bash
         #
         #
         set -ex
 
+        # shellcheck disable=SC2317 # shellcheck calls all the commands in exitfunc unreachable because it is called
+        # via trap
+        exitfunc() {
+            local err="$1"
+            local line="$2"
+            local command="$3"
+            if [ "$err" -ne 0 ] ; then
+                echo -n \
+                  "$0: ERROR '$command' failed at line $line - exited with status $err"
+                touch "$(params.dataDir)/$(params.subdirectory)/error"
+            fi
+            exit 0
+        }
+        # due to set -e, this catches all EXIT and ERR calls and the task should never fail with nonzero exit code
+        trap 'exitfunc $? $LINENO "$BASH_COMMAND"' EXIT
+
+        rm -rf "$(params.dataDir)/$(params.subdirectory)/error"
+        
         # Obtain application from snapshot
-        application=$(jq -rc .application "$(workspaces.data.path)/$(params.snapshotPath)")
+        application=$(jq -rc .application "$(params.dataDir)/$(params.snapshotPath)")
 
         # Extract the key from the JSON file
-        fileUpdates=$(jq -rc "$(params.jsonKey)" "$(workspaces.data.path)/$(params.fileUpdatesPath)")
+        fileUpdates=$(jq -rc "$(params.jsonKey)" "$(params.dataDir)/$(params.fileUpdatesPath)")
 
         TASK_LABEL="internal-services.appstudio.openshift.io/group-id"
         REQUEST_LABEL="internal-services.appstudio.openshift.io/request-id"
         TASK_ID=$(context.taskRun.uid)
         PIPELINERUN_LABEL="internal-services.appstudio.openshift.io/pipelinerun-uid"
 
-        RESULTS_FILE="$(workspaces.data.path)/$(params.resultsDirPath)/file-updates-results.json"
+        RESULTS_FILE="$(params.dataDir)/$(params.resultsDirPath)/file-updates-results.json"
         RESULTS_JSON='{"merge_requests":[]}'
 
         # empty result to start so result is available
@@ -92,7 +200,7 @@ spec:
           echo "=== Updates for repo: ${repo} ==="
 
           echo -en "  Evaluating '{{ }}' expressions..."
-          updatedPaths=$(update-paths -p "${paths}" -f "$(workspaces.data.path)/$(params.snapshotPath)")
+          updatedPaths=$(update-paths -p "${paths}" -f "$(params.dataDir)/$(params.snapshotPath)")
           echo "done"
 
           echo -en "  Creating InternalRequest to produce file-updates..."
@@ -140,3 +248,47 @@ spec:
           fi
           echo -e "=== Finished ===\n"
         done
+    - name: create-trusted-artifact
+      ref:
+        resolver: "git"
+        params:
+          - name: url
+            value: $(params.stepActionGitUrl)
+          - name: revision
+            value: $(params.stepActionGitRevision)
+          - name: pathInRepo
+            value: stepactions/create-trusted-artifact/create-trusted-artifact.yaml
+      params:
+        - name: ociStorage
+          value: $(params.ociStorage)
+        - name: dataDir
+          value: $(params.dataDir)
+        - name: subdirectory
+          value: $(params.subdirectory)
+        - name: sourceDataArtifact
+          value: $(results.sourceDataArtifact.path)
+    - name: patch-source-data-artifact-result
+      ref:
+        resolver: "git"
+        params:
+          - name: url
+            value: $(params.stepActionGitUrl)
+          - name: revision
+            value: $(params.stepActionGitRevision)
+          - name: pathInRepo
+            value: stepactions/patch-source-data-artifact-result/patch-source-data-artifact-result.yaml
+      params:
+        - name: ociStorage
+          value: $(params.ociStorage)
+        - name: sourceDataArtifact
+          value: $(results.sourceDataArtifact.path)
+    - name: fail-on-error
+      image: quay.io/konflux-ci/release-service-utils:e633d51cd41d73e4b3310face21bb980af7a662f
+      script: |
+        #!/usr/bin/env bash
+        set -eu
+
+        if [ -f "$(params.dataDir)/$(params.subdirectory)/error" ]; then
+          echo "Errors encountered"
+          exit 1
+        fi
